
name: acceptance
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pip install poetry
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: "poetry"
          cache-dependency-path: "pyproject.toml"
      - name: Install dependencies
        run: poetry install --no-root
      - name: Check Black
        run: poetry run black --check animationCombiner --diff